name = "afl230-leaderboard"
main = "src/index.ts"
compatibility_date = "2026-06-01"

# Run `npx wrangler kv namespace create BOARD` and paste the id below
kv_namespaces = [
  { binding = "BOARD", id = "d0e7b6ddaa7241d289a26b115ca4589c" }
]
